___

<a href='http://www.pieriandata.com'><img src='../Pierian_Data_Logo.png'/></a>
___
<center><em>Copyright by Pierian Data Inc.</em></center>
<center><em>For more information, visit us at <a href='http://www.pieriandata.com'>www.pieriandata.com</a></em></center>

# Pandas Project Exercise - 

# The Data

The dataset contains a list of all stocks included in the SP500 and associated key financials. <br />

Note that there are multiple viable solutions for most of the tasks!


Acknowledgements
----------------------------
The dataset was originally provided on https://datahub.io/core/s-and-p-500-companies-financials and is licensed under Open Data Commons Public Domain Dedication and License. (https://opendatacommons.org/licenses/pddl/1-0/)

**Task: Import the necessary libraries**

In [3]:
# CODE HERE
import numpy as np
import pandas as pd

**Task: Read the two datasets provided in the current directory (also available in the DATA folder. (The file names are: constituents.csv and constituents-financials.csv)**

In [4]:
# CODE HERE
df=pd.read_csv("constituents.csv")
df1=pd.read_csv("constituents-financials.csv")
df1

,Symbol,Price,Price/Earnings,Dividend Yield,Earnings/Share,52 Week Low,52 Week High,Market Cap,EBITDA,Price/Sales,Price/Book,SEC Filings
0,MMM,222.89,24.31,2.332862,7.92,259.77,175.490,138721055226,9.048000e+09,4.390271,11.34,http://www.sec.gov/cgi-bin/browse-edgar?action...
1,AOS,60.24,27.76,1.147959,1.70,68.39,48.925,10783419933,6.010000e+08,3.575483,6.35,http://www.sec.gov/cgi-bin/browse-edgar?action...
2,ABT,56.27,22.51,1.908982,0.26,64.60,42.280,102121042306,5.744000e+09,3.740480,3.19,http://www.sec.gov/cgi-bin/browse-edgar?action...
3,ABBV,108.48,19.41,2.499560,3.29,125.86,60.050,181386347059,1.031000e+10,6.291571,26.14,http://www.sec.gov/cgi-bin/browse-edgar?action...
4,ACN,150.51,25.47,1.714470,5.44,162.60,114.820,98765855553,5.643228e+09,2.604117,10.62,http://www.sec.gov/cgi-bin/browse-edgar?action...
...,...,...,...,...,...,...,...,...,...,...,...,...
500,XYL,70.24,30.94,1.170079,1.83,76.81,46.860,12915021000,7.220000e+08,2.726209,5.31,http://www.sec.gov/cgi-bin/browse-edgar?action...
501,YUM,76.30,27.25,1.797080,4.07,86.93,62.850,27003303098,2.289000e+09,6.313636,212.08,http://www.sec.gov/cgi-bin/browse-edgar?action...
502,ZBH,115.53,14.32,0.794834,9.01,133.49,108.170,24454698119,2.007400e+09,3.164895,2.39,http://www.sec.gov/cgi-bin/browse-edgar?action...
503,ZION,50.71,17.73,1.480933,2.60,55.61,38.430,10670678640,0.000000e+00,3.794579,1.42,http://www.sec.gov/cgi-bin/browse-edgar?action...
504,ZTS,71.51,32.80,0.682372,1.65,80.13,52.000,35991109776,1.734000e+09,9.280896,18.09,http://www.sec.gov/cgi-bin/browse-edgar?action...

**Task: List all columns of the two datasets. Additionally retrieve the datatype for each column**

In [5]:
# CODE HERE
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 505 entries, 0 to 504
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Symbol          505 non-null    object
 1   Price           505 non-null    float64
 2   Price/Earnings  503 non-null    float64
 3   Dividend Yield  505 non-null    float64
 4   Earnings/Share  505 non-null    float64
 5   52 Week Low     505 non-null    float64
 6   52 Week High    505 non-null    float64
 7   Market Cap      505 non-null    int64
 8   EBITDA          505 non-null    float64
 9   Price/Sales     505 non-null    float64
 10  Price/Book      497 non-null    float64
 11  SEC Filings     505 non-null    object
dtypes: float64(9), int64(1), object(2)
memory usage: 47.5+ KB

**Task: Print the first 5 rows of both datasets**

In [6]:
# CODE HERE
df.head()
df1.head()

,Symbol,Price,Price/Earnings,Dividend Yield,Earnings/Share,52 Week Low,52 Week High,Market Cap,EBITDA,Price/Sales,Price/Book,SEC Filings
0,MMM,222.89,24.31,2.332862,7.92,259.77,175.490,138721055226,9.048000e+09,4.390271,11.34,http://www.sec.gov/cgi-bin/browse-edgar?action...
1,AOS,60.24,27.76,1.147959,1.70,68.39,48.925,10783419933,6.010000e+08,3.575483,6.35,http://www.sec.gov/cgi-bin/browse-edgar?action...
2,ABT,56.27,22.51,1.908982,0.26,64.60,42.280,102121042306,5.744000e+09,3.740480,3.19,http://www.sec.gov/cgi-bin/browse-edgar?action...
3,ABBV,108.48,19.41,2.499560,3.29,125.86,60.050,181386347059,1.031000e+10,6.291571,26.14,http://www.sec.gov/cgi-bin/browse-edgar?action...
4,ACN,150.51,25.47,1.714470,5.44,162.60,114.820,98765855553,5.643228e+09,2.604117,10.62,http://www.sec.gov/cgi-bin/browse-edgar?action...

**Task: Drop the SEC Filings column**

In [7]:
# CODE HERE
df1=df1.drop('SEC Filings', axis=1)
df1

,Symbol,Price,Price/Earnings,Dividend Yield,Earnings/Share,52 Week Low,52 Week High,Market Cap,EBITDA,Price/Sales,Price/Book
0,MMM,222.89,24.31,2.332862,7.92,259.77,175.490,138721055226,9.048000e+09,4.390271,11.34
1,AOS,60.24,27.76,1.147959,1.70,68.39,48.925,10783419933,6.010000e+08,3.575483,6.35
2,ABT,56.27,22.51,1.908982,0.26,64.60,42.280,102121042306,5.744000e+09,3.740480,3.19
3,ABBV,108.48,19.41,2.499560,3.29,125.86,60.050,181386347059,1.031000e+10,6.291571,26.14
4,ACN,150.51,25.47,1.714470,5.44,162.60,114.820,98765855553,5.643228e+09,2.604117,10.62
...,...,...,...,...,...,...,...,...,...,...,...
500,XYL,70.24,30.94,1.170079,1.83,76.81,46.860,12915021000,7.220000e+08,2.726209,5.31
501,YUM,76.30,27.25,1.797080,4.07,86.93,62.850,27003303098,2.289000e+09,6.313636,212.08
502,ZBH,115.53,14.32,0.794834,9.01,133.49,108.170,24454698119,2.007400e+09,3.164895,2.39
503,ZION,50.71,17.73,1.480933,2.60,55.61,38.430,10670678640,0.000000e+00,3.794579,1.42
504,ZTS,71.51,32.80,0.682372,1.65,80.13,52.000,35991109776,1.734000e+09,9.280896,18.09

**Task: Set the Symbol column to the index in the financials dataset**

In [8]:
# CODE HERE
df1=df1.reset_index()
df1=df1.set_index('Symbol')
df1

,index,Price,Price/Earnings,Dividend Yield,Earnings/Share,52 Week Low,52 Week High,Market Cap,EBITDA,Price/Sales,Price/Book
Symbol,,,,,,,,,,,
MMM,0,222.89,24.31,2.332862,7.92,259.77,175.490,138721055226,9.048000e+09,4.390271,11.34
AOS,1,60.24,27.76,1.147959,1.70,68.39,48.925,10783419933,6.010000e+08,3.575483,6.35
ABT,2,56.27,22.51,1.908982,0.26,64.60,42.280,102121042306,5.744000e+09,3.740480,3.19
ABBV,3,108.48,19.41,2.499560,3.29,125.86,60.050,181386347059,1.031000e+10,6.291571,26.14
ACN,4,150.51,25.47,1.714470,5.44,162.60,114.820,98765855553,5.643228e+09,2.604117,10.62
...,...,...,...,...,...,...,...,...,...,...,...
XYL,500,70.24,30.94,1.170079,1.83,76.81,46.860,12915021000,7.220000e+08,2.726209,5.31
YUM,501,76.30,27.25,1.797080,4.07,86.93,62.850,27003303098,2.289000e+09,6.313636,212.08
ZBH,502,115.53,14.32,0.794834,9.01,133.49,108.170,24454698119,2.007400e+09,3.164895,2.39
ZION,503,50.71,17.73,1.480933,2.60,55.61,38.430,10670678640,0.000000e+00,3.794579,1.42
ZTS,504,71.51,32.80,0.682372,1.65,80.13,52.000,35991109776,1.734000e+09,9.280896,18.09

**Task: What are the 10 largest companies according to market cap?**

In [14]:
# CODE HERE
df1.nlargest(10,'Market Cap').filter('Symbol')

Empty DataFrame
Columns: []
Index: [AAPL, GOOGL, GOOG, MSFT, AMZN, FB, JPM, JNJ, XOM, BAC]

**Task: Return all information about the 10 largest companies according by market cap**

In [11]:
# CODE HERE
df1.nlargest(10,'Market Cap').describe().transpose()

,count,mean,std,min,25%,50%,75%,max
index,10.0,1.409000e+02,1.125694e+02,2.700000e+01,3.525000e+01,1.255000e+02,2.425000e+02,3.110000e+02
Price,10.0,4.111520e+02,4.996584e+02,2.974000e+01,9.072750e+01,1.407550e+02,7.940350e+02,1.350500e+03
Price/Earnings,10.0,5.089000e+01,8.654783e+01,1.543000e+01,1.697250e+01,2.356500e+01,3.058500e+01,2.961600e+02
Dividend Yield,10.0,1.353472e+00,1.356073e+00,0.000000e+00,0.000000e+00,1.557771e+00,1.957136e+00,4.003120e+00
Earnings/Share,10.0,7.838000e+00,8.053991e+00,3.900000e-01,2.152500e+00,5.775000e+00,8.475000e+00,2.227000e+01
52 Week Low,10.0,4.742023e+02,5.738627e+02,3.267000e+01,1.013907e+02,1.642100e+02,9.389975e+02,1.498000e+03
52 Week High,10.0,3.059675e+02,3.516702e+02,2.207000e+01,7.744625e+01,1.221350e+02,6.355027e+02,8.243000e+02
Market Cap,10.0,5.558445e+11,1.941483e+11,3.214782e+11,3.614503e+11,6.046482e+11,7.188963e+11,8.095080e+11
EBITDA,10.0,2.886340e+10,2.296415e+10,0.000000e+00,1.770650e+10,2.816900e+10,3.784325e+10,7.938600e+10
Price/Sales,10.0,5.429057e+00,3.281669e+00,1.770194e+00,3.393277e+00,4.279838e+00,6.794432e+00,1.324197e+01
Price/Book,10.0,6.531000e+00,6.741970e+00,1.240000e+00,2.555000e+00,4.720000e+00,6.725000e+00,2.428000e+01

Note: The difference between GOOG and GOOGL is, that GOOG shares have no voting rights

**Task: Drop GOOG**

In [16]:
# CODE HERE
df1.drop(index="GOOG", inplace=True)

KeyError: "['GOOG'] not found in axis"

**Task: How many companies have a dividend yield > 4% ?**

In [13]:
# CODE HERE
count=0
bol=df1['Dividend Yield']>4
for i in bol:
    if(i==True):
        count=count+1
print(count)

37

**Task: What is the mean Earnings per Share for all companies with a market cap > 1e+11**

In [43]:
# CODE HERE
bool_series=df1['Market Cap']>(1e+11)
df1=df1[bool_series]
df1["Earnings/Share"].mean()

5.083461538461538

**Task: How many companies have a positive earnings per shares ratio?**

In [31]:
# CODE HERE
bool_series=df1['Earnings/Share']>0
df2=df1[bool_series]
df2

,Symbol,Price,Price/Earnings,Dividend Yield,Earnings/Share,52 Week Low,52 Week High,Market Cap,EBITDA,Price/Sales,Price/Book,SEC Filings,Market Cap in Billion
0,MMM,222.89,24.31,2.332862,7.92,259.77,175.490,138721055226,9.048000e+09,4.390271,11.34,http://www.sec.gov/cgi-bin/browse-edgar?action...,138.721055
1,AOS,60.24,27.76,1.147959,1.70,68.39,48.925,10783419933,6.010000e+08,3.575483,6.35,http://www.sec.gov/cgi-bin/browse-edgar?action...,10.783420
2,ABT,56.27,22.51,1.908982,0.26,64.60,42.280,102121042306,5.744000e+09,3.740480,3.19,http://www.sec.gov/cgi-bin/browse-edgar?action...,102.121042
3,ABBV,108.48,19.41,2.499560,3.29,125.86,60.050,181386347059,1.031000e+10,6.291571,26.14,http://www.sec.gov/cgi-bin/browse-edgar?action...,181.386347
4,ACN,150.51,25.47,1.714470,5.44,162.60,114.820,98765855553,5.643228e+09,2.604117,10.62,http://www.sec.gov/cgi-bin/browse-edgar?action...,98.765856
...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,XYL,70.24,30.94,1.170079,1.83,76.81,46.860,12915021000,7.220000e+08,2.726209,5.31,http://www.sec.gov/cgi-bin/browse-edgar?action...,12.915021
501,YUM,76.30,27.25,1.797080,4.07,86.93,62.850,27003303098,2.289000e+09,6.313636,212.08,http://www.sec.gov/cgi-bin/browse-edgar?action...,27.003303
502,ZBH,115.53,14.32,0.794834,9.01,133.49,108.170,24454698119,2.007400e+09,3.164895,2.39,http://www.sec.gov/cgi-bin/browse-edgar?action...,24.454698
503,ZION,50.71,17.73,1.480933,2.60,55.61,38.430,10670678640,0.000000e+00,3.794579,1.42,http://www.sec.gov/cgi-bin/browse-edgar?action...,10.670679
504,ZTS,71.51,32.80,0.682372,1.65,80.13,52.000,35991109776,1.734000e+09,9.280896,18.09,http://www.sec.gov/cgi-bin/browse-edgar?action...,35.991110

**Task: Which company pays the highest dividend yield? What was its 52 week high?**

In [16]:
# CODE HERE
df3=df1.sort_values('Dividend Yield',ascending=False)
sf=df3.iloc[0:1]
sf

,index,Price,Price/Earnings,Dividend Yield,Earnings/Share,52 Week Low,52 Week High,Market Cap,EBITDA,Price/Sales,Price/Book
Symbol,,,,,,,,,,,
CTL,99,16.2,8.35,12.661196,1.16,27.61,13.161,18237196861,5.577000e+09,1.479598,1.39

**Task: Return the company with the largest spread between 52 weeks high and low**

In [64]:
# CODE HERE

def spread(a,b):
    return a-b
arr=df1[['52 Week Low' ,'52 Week High']].apply(lambda df1:spread(df1['52 Week Low'],df1['52 Week High']),axis=1)
arr.max()

685.5

**Task: Return all companies whith a price between \\$ 50 and \\$ 100**

In [63]:
# CODE HERE
l1=df1['Price']>50 
l2=df1['Price']<100
l3=l1&l2
l3
l4=df1[l3]
type(l4.filter(['EBITDA']))

pandas.core.frame.DataFrame

**Task: The market cap is really hard to read. Create a new column called "Market Cap in Billion" which shows the market cap in billions**

In [3]:
# CODE HERE
import pandas as pd
df1=pd.read_csv("constituents-financials.csv")
df1['Market Cap in Billion']=(10**(-9))*df1['Market Cap']
df1

,Symbol,Price,Price/Earnings,Dividend Yield,Earnings/Share,52 Week Low,52 Week High,Market Cap,EBITDA,Price/Sales,Price/Book,SEC Filings,Market Cap in Billion
0,MMM,222.89,24.31,2.332862,7.92,259.77,175.490,138721055226,9.048000e+09,4.390271,11.34,http://www.sec.gov/cgi-bin/browse-edgar?action...,138.721055
1,AOS,60.24,27.76,1.147959,1.70,68.39,48.925,10783419933,6.010000e+08,3.575483,6.35,http://www.sec.gov/cgi-bin/browse-edgar?action...,10.783420
2,ABT,56.27,22.51,1.908982,0.26,64.60,42.280,102121042306,5.744000e+09,3.740480,3.19,http://www.sec.gov/cgi-bin/browse-edgar?action...,102.121042
3,ABBV,108.48,19.41,2.499560,3.29,125.86,60.050,181386347059,1.031000e+10,6.291571,26.14,http://www.sec.gov/cgi-bin/browse-edgar?action...,181.386347
4,ACN,150.51,25.47,1.714470,5.44,162.60,114.820,98765855553,5.643228e+09,2.604117,10.62,http://www.sec.gov/cgi-bin/browse-edgar?action...,98.765856
...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,XYL,70.24,30.94,1.170079,1.83,76.81,46.860,12915021000,7.220000e+08,2.726209,5.31,http://www.sec.gov/cgi-bin/browse-edgar?action...,12.915021
501,YUM,76.30,27.25,1.797080,4.07,86.93,62.850,27003303098,2.289000e+09,6.313636,212.08,http://www.sec.gov/cgi-bin/browse-edgar?action...,27.003303
502,ZBH,115.53,14.32,0.794834,9.01,133.49,108.170,24454698119,2.007400e+09,3.164895,2.39,http://www.sec.gov/cgi-bin/browse-edgar?action...,24.454698
503,ZION,50.71,17.73,1.480933,2.60,55.61,38.430,10670678640,0.000000e+00,3.794579,1.42,http://www.sec.gov/cgi-bin/browse-edgar?action...,10.670679
504,ZTS,71.51,32.80,0.682372,1.65,80.13,52.000,35991109776,1.734000e+09,9.280896,18.09,http://www.sec.gov/cgi-bin/browse-edgar?action...,35.991110

**Task: Is there a correlation between the market cap and the Dividend Yield?**

In [6]:
# CODE HERE
df=pd.read_csv("constituents.csv")
lf1=pd.merge(df,df1,how='inner')
lf1

,Symbol,Name,Sector,Price,Price/Earnings,Dividend Yield,Earnings/Share,52 Week Low,52 Week High,Market Cap,EBITDA,Price/Sales,Price/Book,SEC Filings,Market Cap in Billion
0,MMM,3M Company,Industrials,222.89,24.31,2.332862,7.92,259.77,175.490,138721055226,9.048000e+09,4.390271,11.34,http://www.sec.gov/cgi-bin/browse-edgar?action...,138.721055
1,AOS,A.O. Smith Corp,Industrials,60.24,27.76,1.147959,1.70,68.39,48.925,10783419933,6.010000e+08,3.575483,6.35,http://www.sec.gov/cgi-bin/browse-edgar?action...,10.783420
2,ABT,Abbott Laboratories,Health Care,56.27,22.51,1.908982,0.26,64.60,42.280,102121042306,5.744000e+09,3.740480,3.19,http://www.sec.gov/cgi-bin/browse-edgar?action...,102.121042
3,ABBV,AbbVie Inc.,Health Care,108.48,19.41,2.499560,3.29,125.86,60.050,181386347059,1.031000e+10,6.291571,26.14,http://www.sec.gov/cgi-bin/browse-edgar?action...,181.386347
4,ACN,Accenture plc,Information Technology,150.51,25.47,1.714470,5.44,162.60,114.820,98765855553,5.643228e+09,2.604117,10.62,http://www.sec.gov/cgi-bin/browse-edgar?action...,98.765856
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,XYL,Xylem Inc.,Industrials,70.24,30.94,1.170079,1.83,76.81,46.860,12915021000,7.220000e+08,2.726209,5.31,http://www.sec.gov/cgi-bin/browse-edgar?action...,12.915021
501,YUM,Yum! Brands Inc,Consumer Discretionary,76.30,27.25,1.797080,4.07,86.93,62.850,27003303098,2.289000e+09,6.313636,212.08,http://www.sec.gov/cgi-bin/browse-edgar?action...,27.003303
502,ZBH,Zimmer Biomet Holdings,Health Care,115.53,14.32,0.794834,9.01,133.49,108.170,24454698119,2.007400e+09,3.164895,2.39,http://www.sec.gov/cgi-bin/browse-edgar?action...,24.454698
503,ZION,Zions Bancorp,Financials,50.71,17.73,1.480933,2.60,55.61,38.430,10670678640,0.000000e+00,3.794579,1.42,http://www.sec.gov/cgi-bin/browse-edgar?action...,10.670679
504,ZTS,Zoetis,Health Care,71.51,32.80,0.682372,1.65,80.13,52.000,35991109776,1.734000e+09,9.280896,18.09,http://www.sec.gov/cgi-bin/browse-edgar?action...,35.991110

**Task: Merge the financials dataframe with the constituents dataframe**

In [7]:
# CODE HERE
lf1=pd.merge(df1,df,how='inner')
lf1

,Symbol,Price,Price/Earnings,Dividend Yield,Earnings/Share,52 Week Low,52 Week High,Market Cap,EBITDA,Price/Sales,Price/Book,SEC Filings,Market Cap in Billion,Name,Sector
0,MMM,222.89,24.31,2.332862,7.92,259.77,175.490,138721055226,9.048000e+09,4.390271,11.34,http://www.sec.gov/cgi-bin/browse-edgar?action...,138.721055,3M Company,Industrials
1,AOS,60.24,27.76,1.147959,1.70,68.39,48.925,10783419933,6.010000e+08,3.575483,6.35,http://www.sec.gov/cgi-bin/browse-edgar?action...,10.783420,A.O. Smith Corp,Industrials
2,ABT,56.27,22.51,1.908982,0.26,64.60,42.280,102121042306,5.744000e+09,3.740480,3.19,http://www.sec.gov/cgi-bin/browse-edgar?action...,102.121042,Abbott Laboratories,Health Care
3,ABBV,108.48,19.41,2.499560,3.29,125.86,60.050,181386347059,1.031000e+10,6.291571,26.14,http://www.sec.gov/cgi-bin/browse-edgar?action...,181.386347,AbbVie Inc.,Health Care
4,ACN,150.51,25.47,1.714470,5.44,162.60,114.820,98765855553,5.643228e+09,2.604117,10.62,http://www.sec.gov/cgi-bin/browse-edgar?action...,98.765856,Accenture plc,Information Technology
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,XYL,70.24,30.94,1.170079,1.83,76.81,46.860,12915021000,7.220000e+08,2.726209,5.31,http://www.sec.gov/cgi-bin/browse-edgar?action...,12.915021,Xylem Inc.,Industrials
501,YUM,76.30,27.25,1.797080,4.07,86.93,62.850,27003303098,2.289000e+09,6.313636,212.08,http://www.sec.gov/cgi-bin/browse-edgar?action...,27.003303,Yum! Brands Inc,Consumer Discretionary
502,ZBH,115.53,14.32,0.794834,9.01,133.49,108.170,24454698119,2.007400e+09,3.164895,2.39,http://www.sec.gov/cgi-bin/browse-edgar?action...,24.454698,Zimmer Biomet Holdings,Health Care
503,ZION,50.71,17.73,1.480933,2.60,55.61,38.430,10670678640,0.000000e+00,3.794579,1.42,http://www.sec.gov/cgi-bin/browse-edgar?action...,10.670679,Zions Bancorp,Financials
504,ZTS,71.51,32.80,0.682372,1.65,80.13,52.000,35991109776,1.734000e+09,9.280896,18.09,http://www.sec.gov/cgi-bin/browse-edgar?action...,35.991110,Zoetis,Health Care

**Task: Print all sectors. How often does each sector occur?**

In [60]:
# CODE HERE
lf1.filter(['Sector'])
lf1['Sector'].value_counts()

Consumer Discretionary        84
Information Technology        70
Financials                    68
Industrials                   67
Health Care                   61
Consumer Staples              34
Real Estate                   33
Energy                        32
Utilities                     28
Materials                     25
Telecommunication Services     3
Name: Sector, dtype: int64

**Task: Replace Information Technology by "IT"**

In [11]:
#CODE HERE
lf1['Information Technology']:replace(['IT'])

NameError: name 'replace' is not defined

**Task: Add a \$ before the stock price**

In [ ]:
# CODE HERE